add_executable(domain_test domain_test.cpp)
target_link_libraries(domain_test PRIVATE runyard_domain GTest::gtest_main)
gtest_discover_tests(domain_test)
add_executable(postgres_test postgres_test.cpp)
target_link_libraries(postgres_test PRIVATE runyard_postgres GTest::gtest_main)
target_compile_definitions(postgres_test PRIVATE RUNYARD_MIGRATIONS="${PROJECT_SOURCE_DIR}/migrations")
gtest_discover_tests(postgres_test)
add_executable(executor_test executor_test.cpp)
target_link_libraries(executor_test PRIVATE runyard_support GTest::gtest_main)
gtest_discover_tests(executor_test)
add_executable(process_test process_test.cpp)
target_link_libraries(process_test PRIVATE runyard_process GTest::gtest_main)
gtest_discover_tests(process_test)
add_executable(storage_test storage_test.cpp)
target_link_libraries(storage_test PRIVATE runyard_storage GTest::gtest_main)
gtest_discover_tests(storage_test)
