apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: runyard
resources: [../local]
patches:
  - target: {kind: ConfigMap, name: runyard-config}
    patch: |-
      - op: add
        path: /data/RUNYARD_KUBERNETES_GPU_RUNTIME_CLASS
        value: nvidia
